baseurl = "https://www.ying-ish.com/"
languageCode = "en-us"
title = "she will never swims alone"
copyright = "This work is licensed under a Creative Commons Attribution-Non-Commercial ShareAlike 4.0 International License."

# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"
# Add your tracking code to enable Google Analytics

# Posts per page
paginate = 20

[taxonomies]
	tag = "tags"
	album = "albums"
	bookmark = "bookmarks"

[params]
	author = "ying"
	description = "a collection of what's going on in her life"
	opengraph = true
	
	imgurl = "https://raw.githubusercontent.com/wpix/solid-pipix/master/photos/"
	
	comments = true
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	gravatar = "img/avatar.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	# gravatar = "your@email.com"

	copyright = '<a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA Licence</a>'

	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		# email = ""
		# flickr = ""
		github = "https://github.com/wpix/"
		instagram = "https://instagram.com/pi__pix/"
		#pinterest = ""
		#twitter = ""

	[params.staticman] #[params.comments.staticman]
		api = "https://dev.staticman.net/v3/entry/github/wpix/swnsa/master/comments"
		# pulls = "https://github.com/bsag/wow/pulls"
		maxDepth = 2

	[params.staticman.recaptcha]
      siteKey = "6Lfg0aEUAAAAALJk55EHef1QCvhDm6oTy4huxHbe"
      secret = "6Lfg0aEUAAAAAPqB9w_LzmN7zF8XDF-5tDu0zpMR"

  [params.valine]
    enable = true
    appId = 'tbBm1LW7zwXq979I4cbUfrr1-gzGzoHsz'
    appKey = 'JYAlTvkWuE1NN8S7VBSChzvp'
    placeholder = 'Say something ...'
    visitor = true






